### ISSUE TITLE
Allow use of an ssh tunnel

### ISSUE THREAD

**Issue by flungo** [cnelson/python-fleet#1]
Implement the ability to provide a tunnel to the client object to initialise a tunnelled connection. Essentially the same functionality as the `--tunnel` flag or `FLEETCTL_TUNNEL` environment variable for the official `fleetctl` tool.

**Comment by cnelson** [comment]
There's a mostly untested version of this in https://github.com/cnelson/python-fleet/commit/32145ca9b11ef3cf8450e3c7e80e29968c7a7a5e 

Still needs unit tests + waiting on https://github.com/paramiko/paramiko/issues/544 to support unix domain forwarding.
